import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#bec6e0",
        "primary-container": "#0f172a",
        "surface-container-low": "#1b1b1d",
        "surface-glass": "rgba(15, 23, 42, 0.75)",
        "on-primary-container": "#798098",
        "outline-variant": "#45464d",
        "tertiary-fixed": "#d8e2ff",
        "surface-container-lowest": "#0e0e10",
        "secondary": "#bec6e0",
        "on-tertiary-fixed-variant": "#2c4677",
        "secondary-container": "#3e465c",
        "status-emergency": "#ffb4ab",
        "background": "#131315",
        "on-primary-fixed": "#131b2e",
        "surface": "#131315",
        "inverse-surface": "#e5e1e4",
        "surface-dim": "#131315",
        "surface-bright": "#39393b",
        "on-primary": "#283044",
        "on-secondary": "#283044",
        "surface-container-highest": "#353437",
        "status-success": "#bec6e0",
        "tertiary": "#adc6ff",
        "on-secondary-container": "#adb5ce",
        "surface-variant": "#353437",
        "secondary-fixed": "#dae2fd",
        "surface-container": "#1f1f21",
        "surface-container-high": "#2a2a2c",
        "error-container": "#93000a",
        "on-tertiary": "#122f5f",
        "on-error": "#690005",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary-fixed-variant": "#3e465c",
        "surface-tint": "#bec6e0",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#131b2e",
        "on-tertiary-container": "#6880b5",
        "outline": "#909097",
        "on-background": "#e5e1e4",
        "inverse-on-surface": "#303032",
        "on-surface": "#e5e1e4",
        "on-surface-variant": "#c6c6cd",
        "border-glass": "rgba(255, 255, 255, 0.12)",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed-variant": "#3f465c",
        "inverse-primary": "#565e74",
        "error": "#ffb4ab",
        "primary": "#bec6e0",
        "tertiary-fixed-dim": "#adc6ff",
        "status-warning": "#ffb690",
        "on-tertiary-fixed": "#001a42",
        "tertiary-container": "#00163a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "panel-padding": "24px",
        "component-gap": "16px",
        "margin-page": "48px",
        "unit": "4px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "display-lg": ["var(--font-inter)", "sans-serif"],
        "display-xl": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "data-mono": ["var(--font-jetbrains-mono)", "monospace"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
        "label-caps": ["var(--font-jetbrains-mono)", "monospace"],
        "title-lg": ["var(--font-inter)", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-xl": ["64px", { lineHeight: "72px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
};
export default config;
